/** Kenney Car Kit (CC0) — https://kenney.nl/assets/car-kit */
const K = './assets/vehicles';

export const CARS = [
  {
    id: 'sport',
    name: 'Sports Sedan',
    tag: 'sedan-sports.glb',
    color: 0xff2222,
    accent: 0x1a1418,
    body: 'coupe',
    model: `${K}/sedan-sports.glb`,
    modelLength: 4.2,
    modelYaw: Math.PI / 2,
    mass: 1080,
    power: 12500,
    top: 52,
    grip: 13.2,
    steer: 0.58,
    wheelbase: 2.38,
  },
  {
    id: 'hatch',
    name: 'Sports Hatch',
    tag: 'hatchback-sports.glb',
    color: 0x3388dd,
    accent: 0x1a2430,
    body: 'hatch',
    model: `${K}/hatchback-sports.glb`,
    modelLength: 4.0,
    modelYaw: Math.PI / 2,
    mass: 1180,
    power: 9200,
    top: 42,
    grip: 11.5,
    steer: 0.52,
    wheelbase: 2.45,
  },
  {
    id: 'sedan',
    name: 'Sedan',
    tag: 'sedan.glb',
    color: 0xd0d8d0,
    accent: 0x3a4038,
    body: 'wagon',
    model: `${K}/sedan.glb`,
    modelLength: 4.4,
    modelYaw: Math.PI / 2,
    mass: 1420,
    power: 8800,
    top: 40,
    grip: 10.8,
    steer: 0.46,
    wheelbase: 2.85,
  },
  {
    id: 'race',
    name: 'Race Car',
    tag: 'race.glb',
    color: 0xffcc22,
    accent: 0x3a2818,
    body: 'convertible',
    model: `${K}/race.glb`,
    modelLength: 4.1,
    modelYaw: Math.PI / 2,
    mass: 1260,
    power: 7600,
    top: 36,
    grip: 9.6,
    steer: 0.5,
    wheelbase: 2.55,
  },
  {
    id: 'van',
    name: 'Van',
    tag: 'van.glb',
    color: 0xe8e0d0,
    accent: 0x5a4030,
    body: 'van',
    model: `${K}/van.glb`,
    modelLength: 4.8,
    modelYaw: Math.PI / 2,
    mass: 1680,
    power: 6400,
    top: 32,
    grip: 8.8,
    steer: 0.42,
    wheelbase: 3.1,
  },
  {
    id: 'suv',
    name: 'SUV',
    tag: 'suv.glb',
    color: 0x889898,
    accent: 0x2a3038,
    body: 'suv',
    model: `${K}/suv.glb`,
    modelLength: 4.5,
    modelYaw: Math.PI / 2,
    mass: 1560,
    power: 9800,
    top: 38,
    grip: 10.2,
    steer: 0.48,
    wheelbase: 2.78,
  },
];

export const DEFAULT_CAR_ID = 'sport';
